name: "My Python Action"
description: "A custom action using Python"
inputs:
  name:
    description: "Name to greet"
    required: true
    default: "World"
outputs:
  greeting:
    description: "The greeting message"
runs:
  using: "python"
  main: "main.py"
