on:
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: zukash/greetinig@main
        with:
          name: "GitHub Actions"
      - run: echo ${{ steps.test-action.outputs.greeting }}
