on:
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: actions/checkout@v2
      #   with:
      #     repository: zukash/greeting
      #     path: ${RUNNER_TEMP}
      - name: hoge
        run: |
          pwd
          ls -la
          echo ${RUNNER_TEMP}

